### ISSUE TITLE
Failed to parse json

### ISSUE THREAD

**Issue by dersch81** [PtrBld/MMM-Podcast#2]
It is me again :)

> - ~/MagicMirror/modules/MMM-Podcast $ npm install
> - npm ERR! Linux 4.4.9-v7+
> - npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
> - npm ERR! node v6.2.0
> - npm ERR! npm  v3.8.9
> - npm ERR! file /home/pi/MagicMirror/modules/MMM-Podcast/package.json
> ## \- npm ERR! code EJSONPARSE
> - npm ERR! Failed to parse json
> - npm ERR! Trailing comma in array at 14:3
> - npm ERR!   ],
> - npm ERR!   ^
> - npm ERR! File: /home/pi/MagicMirror/modules/MMM-Podcast/package.json
> - npm ERR! Failed to parse package.json data.
> - npm ERR! package.json must be actual JSON, not just JavaScript.
> - npm ERR!
> - npm ERR! This is not a bug in npm.
> ## \- npm ERR! Tell the package author to fix their package.json file. JSON.parse
> - npm ERR! Please include the following file with any support request:
> - npm ERR!     /home/pi/MagicMirror/modules/MMM-Podcast/npm-debug.log

```
- cat npm-debug.log
- 0 info it worked if it ends with ok
- 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
- 2 info using npm@3.8.9
- 3 info using node@v6.2.0
- 4 silly loadCurrentTree Starting
- 5 silly install loadCurrentTree
- 6 silly install readLocalPackageData
- 7 silly rollbackFailedOptional Starting
- 8 silly rollbackFailedOptional Finishing
- 9 silly runTopLevelLifecycles Starting
- 10 silly runTopLevelLifecycles Finishing
- 11 silly install printInstalled
- 12 verbose stack Error: Failed to parse json
- 12 verbose stack Trailing comma in array at 14:3
- 12 verbose stack   ],
- 12 verbose stack   ^
- 12 verbose stack     at parseError (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:390:11)
- 12 verbose stack     at parseJson (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:79:23)
- 12 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:48:5
- 12 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
- 12 verbose stack     at tryToString (fs.js:449:3)
- 12 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
- 13 verbose cwd /home/pi/MagicMirror/modules/MMM-Podcast
- 14 error Linux 4.4.9-v7+
- 15 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
- 16 error node v6.2.0
- 17 error npm  v3.8.9
- 18 error file /home/pi/MagicMirror/modules/MMM-Podcast/package.json
- 19 error code EJSONPARSE
- 20 error Failed to parse json
- 20 error Trailing comma in array at 14:3
- 20 error   ],
- 20 error   ^
- 21 error File: /home/pi/MagicMirror/modules/MMM-Podcast/package.json
- 22 error Failed to parse package.json data.
- 22 error package.json must be actual JSON, not just JavaScript.
- 22 error
- 22 error This is not a bug in npm.
- 22 error Tell the package author to fix their package.json file. JSON.parse
- 23 verbose exit [ 1, true ]
```

**Comment by PtrBld** [comment]
Sorry same issues... Should be fixed as well 😊

**Comment by dersch81** [comment]
Works! :)
